#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>

# src code references
source='
  ../redirect_io.h
  ../calculate_pentagon.h
  ../calculate_pentagon.cpp
  ../number.h
  ../number.cpp
  ../quick_sort.h
  ../quick_sort.cpp
  ../search_odds.h
  ../search_odds.cpp
  ../composite_figure.h
  ../composite_figure.cpp
  ../catch_test_1_1/test_1_1.cpp
  ../catch_test_2_1/test_2_1.cpp
  ../catch_test_3_1/test_3_1.cpp
  ../catch_test_4_1/test_4_1.cpp
  ../catch_test_5_1/test_5_1.cpp
  '

cppcheck ${source} -x c++ --enable=all --verbose --error-exitcode=1 --suppressions-list=suppressions.txt --check-config