#!/usr/bin/env bash

#  execute the test -- you would most likely execute on submitted file
#  for example: cppcheck ../student_file.h <options>

# src code references
source='
  ../redirect_io.h
  ../calculate_pentagon.h
  ../calculate_pentagon.cpp
  ../number.h
  ../number.cpp
  ../quick_sort.h
  ../quick_sort.cpp
  ../search_odds.h
  ../search_odds.cpp
  ../composite_figure.h
  ../composite_figure.cpp
  '

cppcheck ${source} -x c++ --enable=all --verbose --error-exitcode=1 --suppressions-list=suppressions.txt